# Generated by Django 4.2.28 on 2026-03-07 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('certificate', 'Certificate')], default='undergraduate', max_length=50)),
                ('college', models.CharField(choices=[('cas', 'College of Arts & Sciences'), ('cit', 'College of Industrial Technology'), ('cted', 'College of Teacher Education'), ('ccje', 'College of Criminal Justice Education'), ('cba', 'College of Business Administration'), ('caf', 'College of Agriculture & Forestry')], max_length=50)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
