# Generated by Django 4.2.28 on 2026-03-14 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('college', models.CharField(choices=[('cas', 'College of Arts & Sciences'), ('cit', 'College of Industrial Technology'), ('cted', 'College of Teacher Education'), ('ccje', 'College of Criminal Justice Education'), ('cba', 'College of Business Administration'), ('caf', 'College of Agriculture & Forestry')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('college', models.CharField(choices=[('cas', 'College of Arts & Sciences'), ('cit', 'College of Industrial Technology'), ('cted', 'College of Teacher Education'), ('ccje', 'College of Criminal Justice Education'), ('cba', 'College of Business Administration'), ('caf', 'College of Agriculture & Forestry')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('onleave', 'On Leave'), ('retired', 'Retired')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'ordering': ['name'],
            },
        ),
    ]
