# Generated by Django 4.2.28 on 2026-03-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_facility_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='college',
            field=models.CharField(choices=[('all', 'All Colleges'), ('cas', 'College of Arts & Sciences'), ('cit', 'College of Industrial Technology'), ('cted', 'College of Teacher Education'), ('ccje', 'College of Criminal Justice Education'), ('cba', 'College of Business Administration'), ('caf', 'College of Agriculture & Forestry')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('news', 'News'), ('update', 'Update'), ('alumni', 'Alumni'), ('award', 'Award'), ('general', 'General Post')], default='general', max_length=20),
        ),
    ]
