# Generated by Django 4.2.28 on 2026-03-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_post_author_post_college_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
