# Generated by Django 4.2.28 on 2026-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_academiccalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='calendar/pdf/'),
        ),
    ]
