# Generated by Django 4.2.28 on 2026-03-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_academiccalendar_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
