# Generated by Django 4.2.28 on 2026-03-15 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_achievement_achievement_date_achievement_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=20)),
                ('dean', models.CharField(max_length=255)),
                ('total_students', models.IntegerField(default=0)),
                ('programs_offered', models.IntegerField(default=0)),
                ('qualified_instructors', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, help_text='List of colleges/departments under this college')),
                ('image', models.ImageField(blank=True, null=True, upload_to='colleges/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
