# Generated by Django 4.2.28 on 2026-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=255, unique=True),
        ),
    ]
