# Generated by Django 4.2.28 on 2026-03-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_mediaupload_remove_program_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The NORSU-BSC Alumni Association', max_length=255)),
                ('content', models.TextField()),
                ('mission', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni/about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni About',
            },
        ),
    ]
