# Generated by Django 4.2.28 on 2026-03-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alumnisuccessstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniabout',
            name='vision',
            field=models.TextField(default='A globally recognized state university.'),
        ),
    ]
