# Generated by Django 4.2.28 on 2026-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alumniabout_vision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumniabout',
            name='vision',
        ),
        migrations.AddField(
            model_name='alumni',
            name='latin_honors',
            field=models.CharField(blank=True, choices=[('', 'No Latin Honor'), ('Summa Cum Laude', 'Summa Cum Laude'), ('Magna Cum Laude', 'Magna Cum Laude'), ('Cum Laude', 'Cum Laude')], default='', max_length=50),
        ),
    ]
