# Generated by Django 4.2.28 on 2026-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_alumni_email_remove_alumniabout_vision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniabout',
            name='vision',
            field=models.TextField(default='A globally recognized state university.'),
        ),
    ]
